# レッスン 03  Pytorch Prerequisites

Pytorchを学ぶには、まず基本的なスキルを習得する必要があります。すべての機械学習手法はデータから情報を抽出することに関わっています。そのため、まずデータの保存、操作、前処理など、データに関する実用的なスキルを学びます。

機械学習では通常、大規模なデータセットを扱う必要があります。あるデータセットを表として捉えることができ、表の行はサンプルに対応し、列は属性に対応します。線形代数は表形式データを扱うための手法を提供してくれます。本書では詳細には立ち入らず、行列演算の基本原理とその実装に重点を置きます。

深層学習は最適化に関する学習です。パラメータを持つモデルに対して、データに最もよく適合するモデルを見つけたいと考えます。アルゴリズムの各ステップにおいて、パラメータをどのように調整するかを決定するには、微積分の知識が少し必要です。本章ではこれらの知識を簡潔に紹介します。幸いなことに、autogradパッケージが自動的に微分を計算してくれます。本章ではこれについても紹介します。

機械学習はまた、予測をどのように行うかに関わります。観測された情報が与えられたとき、ある未知の属性の取り得る値は何でしょうか?不確実な状況下で厳密な推論を行うには、確率の言語を借用する必要があります。

最後に、公式ドキュメントには本レッスン以外の豊富な説明と例が提供されています。本章の最後では、公式ドキュメントで必要な情報を検索する方法を示します。

## Section 1 データ操作

様々なデータ操作を行うには、データを保存および操作する何らかの方法が必要です。通常、次の2つの重要なことを行う必要があります。
(1)データの取得、(2)データをコンピュータに読み込んだ後の処理。データを保存する方法がなければ、データを取得することは意味がありません。

まず、n次元配列、別名テンソル(tensor)を紹介します。PythonのNumPy計算パッケージを使用したことがある読者にとって、本節は馴染み深いものでしょう。どの深層学習フレームワークを使用するにしても、そのテンソルクラス(MXNetではndarray、PyTorchとTensorFlowではTensor)はNumpyのndarrayに似ています。しかし、深層学習フレームワークはNumpyのndarrayよりもいくつかの重要な機能を追加しています。第一に、GPUが計算の高速化をよくサポートしているのに対し、NumPyはCPU計算のみをサポートしています。第二に、テンソルクラスは自動微分をサポートしています。これらの機能により、テンソルクラスは深層学習により適したものとなっています。特に断りのない限り、本書で述べるテンソルはすべてテンソルクラスのインスタンスを指します。

本節の目標は、レッスンを読み進める過程で使用する基本的な数値計算ツールを理解し、実行できるようにすることです。

まず、torchをインポートします。PyTorchと呼ばれていますが、コード内ではpytorchではなくtorchを使用することに注意してください。

In [12]:
import torch

テンソルは数値で構成される配列を表し、この配列は複数の次元を持つ可能性があります。1つの軸を持つテンソルは数学的にベクトル(vector)に対応します。2つの軸を持つテンソルは数学的に行列(matrix)に対応します。2つ以上の軸を持つテンソルには特別な数学的名称はありません。

まず、arangeを使用して行ベクトルxを作成できます。この行ベクトルは0から始まる最初の12個の整数を含み、これらはデフォルトで整数として作成されます。浮動小数点数型として作成することも指定できます。テンソル内の各値はテンソルの要素(element)と呼ばれます。例えば、テンソルxには12個の要素があります。特に指定しない限り、新しいテンソルはメモリに保存され、CPUベースの計算を採用します。

In [13]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

テンソルのshape属性を通じて、テンソルの形状(各軸に沿った長さ)にアクセスできます。

In [14]:
x.shape

torch.Size([12])

テンソル内の要素の総数、つまり形状のすべての要素の積だけを知りたい場合は、そのサイズ(size)を確認できます。ここで扱っているのはベクトルなので、そのshapeとsizeは同じです。

In [15]:
x.numel()

12

要素の数と要素の値を変えずにテンソルの形状を変更したい場合は、reshape関数を呼び出すことができます。例えば、テンソルxを形状(12,)の行ベクトルから形状(3,4)の行列に変換できます。この新しいテンソルは変換前と同じ値を含みますが、3行4列の行列として見なされます。重要な点として、テンソルの形状は変わりましたが、その要素の値は変わっていません。注意すべきは、テンソルの形状を変更しても、テンソルのサイズは変わらないということです。

In [17]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

形状を変更するために各次元を手動で指定する必要はありません。つまり、目標の形状が(高さ、幅)である場合、幅を知った後、高さは自動的に計算されるため、自分で除算を行う必要はありません。上記の例では、3行の行列を取得するために、3行4列であることを手動で指定しました。幸いなことに、-1を使用してこの自動計算機能を呼び出すことができます。つまり、x.reshape(3,4)の代わりにx.reshape(-1,4)またはx.reshape(3,-1)を使用できます。

## 練習問題1

以下の要件を満たすコードを書いてください。

torch.arange()を使用して、0から59までの60個の整数を含むテンソルdataを作成してください。

このテンソルを以下の3つの異なる形状に変換し、それぞれ出力してください：

- 形状(5, 12)の行列matrix_a（-1を使って行数を自動計算）
- 形状(10, 6)の行列matrix_b（-1を使って列数を自動計算）
- 形状(3, 4, 5)の3次元テンソルtensor_c（-1を使って最初の次元を自動計算）


各変換後のテンソルのshapeを出力して確認してください。

時には、全て0、全て1、その他の定数、または特定の分布からランダムにサンプリングされた数値を使用して行列を初期化したい場合があります。形状が(2,3,4)で、すべての要素が0に設定されたテンソルを作成できます。コードは次のとおりです。

In [20]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

時には、特定の確率分布からランダムにサンプリングすることで、テンソルの各要素の値を取得したい場合があります。例えば、ニューラルネットワークのパラメータとして配列を構築する際、通常はパラメータの値をランダムに初期化します。以下のコードは、形状が(3,4)のテンソルを作成します。その中の各要素は、平均0、標準偏差1の標準ガウス分布(正規分布)からランダムにサンプリングされます。

In [22]:
torch.randn(3, 4)

tensor([[ 1.2633, -1.1481,  1.3903, -1.1236],
        [-0.7373, -0.4752, -1.3118,  2.2922],
        [ 0.7514, -1.5083,  1.3942, -0.6517]])

数値を含むPythonのリスト（またはネストされたリスト）を提供することで、必要なテンソルの各要素に確定した値を割り当てることもできます。ここで、最も外側のリストは軸0に対応し、内側のリストは軸1に対応します。

In [23]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

私たちの関心はデータの読み取りと書き込みに限定されません。これらのデータに対して数学演算を実行したいと考えており、その中で最も単純で有用な操作は要素ごと(elementwise)の演算です。これらは標準的なスカラー演算子を配列の各要素に適用します。2つの配列を入力とする関数の場合、要素ごとの演算は2つの配列内の各ペアの位置に対応する要素に二項演算子を適用します。スカラーからスカラーへの任意の関数に基づいて、要素ごとの関数を作成できます。
同じ形状を持つ任意のテンソルに対して、一般的な標準算術演算子（+、-、*、/、**）はすべて要素ごとの演算に昇格できます。同じ形状の任意の2つのテンソルに対して要素ごとの操作を呼び出すことができます。以下の例では、カンマを使用して5つの要素を持つタプルを表し、各要素は要素ごとの操作の結果です。(**演算子は累乗演算です)

In [24]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

"要素ごと"の方式では、累乗のような単項演算子を含む、より多くの計算を適用できます。

In [25]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 練習問題2

以下の要件を満たすコードを書いてください。

- 形状が(3, 3)で、1から9までの整数を含むテンソルaを作成してください。
``
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
``
- 形状が(3, 3)で、すべての要素が2であるテンソルbを作成してください。
``
[[2, 2, 2],
[2, 2, 2],
[2, 2, 2]]
``
- 以下の3つの演算を実行し、結果を出力してください：
1. aとbの足し算
2. aとbの掛け算（要素ごと）
3. aの各要素を2乗したもの（for文不使用）

要素ごとの計算以外にも、ベクトルの内積や行列の乗算を含む線形代数演算を実行できます。線形代数の重要な内容についてはSection3で説明します。

また、複数のテンソルを連結(concatenate)することもできます。それらを端から端まで積み重ねて、より大きなテンソルを形成します。テンソルのリストを提供し、どの軸に沿って連結するかを指定するだけです。

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

時には、論理演算子を通じて二値テンソルを構築したい場合があります。X == Yを例にすると、各位置について、XとYがその位置で等しい場合、新しいテンソルの対応する項の値は1になります。これは、論理文X == Yがその位置で真であることを意味し、そうでない場合はその位置は0になります。

In [27]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

テンソル内のすべての要素を合計すると、単一要素のテンソルが生成されます。

In [28]:
X.sum()

tensor(66.)

## 練習問題3

以下の要件を満たすコードを書いてください

以下の操作を実行し、結果を出力してください：

- aとbを軸0（縦方向）に沿って連結したテンソルc
- aとbを軸1（横方向）に沿って連結したテンソルd
- aの要素が2より大きいかどうかを判定する二値テンソルe
- テンソルaのすべての要素の合計

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])