# レッスン 03  Pytorch Prerequisites

Pytorchを学ぶには、まず基本的なスキルを習得する必要があります。すべての機械学習手法はデータから情報を抽出することに関わっています。そのため、まずデータの保存、操作、前処理など、データに関する実用的なスキルを学びます。

最後に、公式ドキュメントには本レッスン以外の豊富な説明と例が提供されています。本レッスンの最後では、公式ドキュメントで必要な情報を検索する方法を示します。

## Section 1 データ操作

様々なデータ操作を行うには、データを保存および操作する何らかの方法が必要です。

まず、n次元配列、別名テンソル(tensor)を紹介します。PythonのNumPy計算パッケージを使用したことがある読者にとって、本節は馴染み深いものでしょう。どの深層学習フレームワークを使用するにしても、そのテンソルクラス(MXNetではndarray、PyTorchとTensorFlowではTensor)はNumpyのndarrayに似ています。しかし、深層学習フレームワークはNumpyのndarrayよりもいくつかの重要な機能を追加しています。第一に、GPUが計算の高速化をよくサポートしているのに対し、NumPyはCPU計算のみをサポートしています。第二に、テンソルクラスは自動微分をサポートしています。これらの機能により、テンソルクラスは深層学習により適したものとなっています。特に断りのない限り、本レッスンで述べるテンソルはすべてテンソルクラスのインスタンスを指します。

本レッスンの目標は、レッスンを読み進める過程で使用する基本的な数値計算ツールを理解し、実行できるようにすることです。

まず、torchをインポートします。PyTorchと呼ばれていますが、コード内ではpytorchではなくtorchを使用することに注意してください。

In [3]:
import torch

### はじめに

テンソルは数値で構成される配列を表し、この配列は複数の次元を持つ可能性があります。1つの軸を持つテンソルは数学的にベクトル(vector)に対応します。2つの軸を持つテンソルは数学的に行列(matrix)に対応します。2つ以上の軸を持つテンソルには特別な数学的名称はありません。

まず、arangeを使用して行ベクトルxを作成できます。この行ベクトルは0から始まる最初の12個の整数を含み、これらはデフォルトで整数として作成されます。浮動小数点数型として作成することも指定できます。テンソル内の各値はテンソルの要素(element)と呼ばれます。例えば、テンソルxには12個の要素があります。特に指定しない限り、新しいテンソルはメモリに保存され、CPUベースの計算を採用します。

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

テンソルのshape属性を通じて、テンソルの形状(各軸に沿った長さ)にアクセスできます。

In [5]:
x.shape

torch.Size([12])

テンソル内の要素の総数、つまり形状のすべての要素の積だけを知りたい場合は、そのサイズ(size)を確認できます。ここで扱っているのはベクトルなので、そのshapeとsizeは同じです。

In [6]:
x.numel()

12

要素の数と要素の値を変えずにテンソルの形状を変更したい場合は、reshape関数を呼び出すことができます。例えば、テンソルxを形状(12,)の行ベクトルから形状(3,4)の行列に変換できます。この新しいテンソルは変換前と同じ値を含みますが、3行4列の行列として見なされます。重要な点として、テンソルの形状は変わりましたが、その要素の値は変わっていません。注意すべきは、テンソルの形状を変更しても、テンソルのサイズは変わらないということです。

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

形状を変更するために各次元を手動で指定する必要はありません。つまり、目標の形状が(高さ、幅)である場合、幅を知った後、高さは自動的に計算されるため、自分で除算を行う必要はありません。上記の例では、3行の行列を取得するために、3行4列であることを手動で指定しました。幸いなことに、-1を使用してこの自動計算機能を呼び出すことができます。つまり、x.reshape(3,4)の代わりにx.reshape(-1,4)またはx.reshape(3,-1)を使用できます。

### 練習問題1

以下の要件を満たすコードを書いてください。

torch.arange()を使用して、0から59までの60個の整数を含むテンソルdataを作成してください。

このテンソルを以下の3つの異なる形状に変換し、それぞれ出力してください：

- 形状(5, 12)の行列matrix_a（-1を使って行数を自動計算）
- 形状(10, 6)の行列matrix_b（-1を使って列数を自動計算）
- 形状(3, 4, 5)の3次元テンソルtensor_c（-1を使って最初の次元を自動計算）


各変換後のテンソルのshapeを出力して確認してください。

時には、全て0、全て1、その他の定数、または特定の分布からランダムにサンプリングされた数値を使用して行列を初期化したい場合があります。形状が(2,3,4)で、すべての要素が0に設定されたテンソルを作成できます。コードは次のとおりです。

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

時には、特定の確率分布からランダムにサンプリングすることで、テンソルの各要素の値を取得したい場合があります。例えば、ニューラルネットワークのパラメータとして配列を構築する際、通常はパラメータの値をランダムに初期化します。以下のコードは、形状が(3,4)のテンソルを作成します。その中の各要素は、平均0、標準偏差1の標準ガウス分布(正規分布)からランダムにサンプリングされます。

In [10]:
torch.randn(3, 4)

tensor([[-1.1513, -0.0466, -0.3376, -1.4045],
        [-0.3713,  0.4517,  0.4350,  1.2027],
        [ 0.4861, -0.9455, -0.6271,  0.0790]])

数値を含むPythonのリスト（またはネストされたリスト）を提供することで、必要なテンソルの各要素に確定した値を割り当てることもできます。ここで、最も外側のリストは軸0に対応し、内側のリストは軸1に対応します。

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 演算子

私たちの関心はデータの読み取りと書き込みに限定されません。これらのデータに対して数学演算を実行したいと考えており、その中で最も単純で有用な操作は要素ごと(elementwise)の演算です。これらは標準的なスカラー演算子を配列の各要素に適用します。2つの配列を入力とする関数の場合、要素ごとの演算は2つの配列内の各ペアの位置に対応する要素に二項演算子を適用します。スカラーからスカラーへの任意の関数に基づいて、要素ごとの関数を作成できます。
同じ形状を持つ任意のテンソルに対して、一般的な標準算術演算子（+、-、*、/、**）はすべて要素ごとの演算に昇格できます。同じ形状の任意の2つのテンソルに対して要素ごとの操作を呼び出すことができます。以下の例では、カンマを使用して5つの要素を持つタプルを表し、各要素は要素ごとの操作の結果です。(**演算子は累乗演算です)

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

"要素ごと"の方式では、累乗のような単項演算子を含む、より多くの計算を適用できます。

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### 練習問題2

以下の要件を満たすコードを書いてください。

- 形状が(3, 3)で、1から9までの整数を含むテンソルaを作成してください。
``
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
``
- 形状が(3, 3)で、すべての要素が2であるテンソルbを作成してください。
``
[[2, 2, 2],
[2, 2, 2],
[2, 2, 2]]
``
- 以下の3つの演算を実行し、結果を出力してください：
1. aとbの足し算
2. aとbの掛け算（要素ごと）
3. aの各要素を2乗したもの（for文不使用）

要素ごとの計算以外にも、ベクトルの内積や行列の乗算を含む線形代数演算を実行できます。

また、複数のテンソルを連結(concatenate)することもできます。それらを端から端まで積み重ねて、より大きなテンソルを形成します。テンソルのリストを提供し、どの軸に沿って連結するかを指定するだけです。

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

時には、論理演算子を通じて二値テンソルを構築したい場合があります。X == Yを例にすると、各位置について、XとYがその位置で等しい場合、新しいテンソルの対応する項の値は1になります。これは、論理文X == Yがその位置で真であることを意味し、そうでない場合はその位置は0になります。

In [15]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

テンソル内のすべての要素を合計すると、単一要素のテンソルが生成されます。

In [16]:
X.sum()

tensor(66.)

### 練習問題3

以下の要件を満たすコードを書いてください

以下の操作を実行し、結果を出力してください：

- aとbを軸0（縦方向）に沿って連結したテンソルc
- aとbを軸1（横方向）に沿って連結したテンソルd
- aの要素が2より大きいかどうかを判定する二値テンソルe
- テンソルaのすべての要素の合計

In [17]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

### ブロードキャスト

上記の部分では、同じ形状の2つのテンソルに対して要素ごとの操作を実行する方法を見てきました。場合によっては、形状が異なっていても、ブロードキャスト機構(broadcasting mechanism)を呼び出すことで要素ごとの操作を実行できます。この機構は次のように機能します。

1. 要素を適切に複製して1つまたは2つの配列を拡張し、変換後に2つのテンソルが同じ形状を持つようにします。
2. 生成された配列に対して要素ごとの操作を実行します。

ほとんどの場合、配列内の長さが1の軸に沿ってブロードキャストを行います。次の例のように：

In [18]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

aとbはそれぞれ3×1と1×2の行列であるため、それらを足し合わせようとすると形状が一致しません。2つの行列をより大きな行列にブロードキャストします。次のように：行列aは列を複製し、行列bは行を複製してから、要素ごとに加算します。

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### インデックスとスライス
他のPython配列と同様に、テンソル内の要素はインデックスを通じてアクセスできます。他のPython配列と同じように、最初の要素のインデックスは0で、最後の要素のインデックスは-1です。範囲を指定して、最初の要素と最後の要素の前までを含めることができます。

以下のように、[-1]を使用して最後の要素を選択でき、[1:3]を使用して2番目と3番目の要素を選択できます。

In [21]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

読み取り以外にも、インデックスを指定して行列に要素を書き込むこともできます。

In [22]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

複数の要素に同じ値を割り当てたい場合、すべての要素をインデックスで指定してから値を割り当てるだけです。例えば、`[0:2, :]`は第1行と第2行にアクセスし、ここで":"は軸1(列)に沿ったすべての要素を表します。ここでは行列のインデックスについて議論していますが、これはベクトルや2次元以上のテンソルにも適用されます。

In [23]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 練習問題4

以下の要件を満たすコードを書いてください。

1. 形状が(4, 3)のテンソル`matrix`を作成してください。値は0から11までの整数とします。

2. 形状が(1, 3)のテンソル`row_vec`を作成してください。値は`[10, 20, 30]`とします。

3. ブロードキャストを使用して、`matrix`と`row_vec`を足し合わせた結果を`result`に保存してください。

4. `result`の2行目と3行目（インデックス1と2）のすべての列を、値100で上書きしてください。

5. 以下を確認してください：
   - 元の`matrix`のメモリアドレス（`id(matrix)`）
   - ステップ3の後の`result`のメモリアドレス
   - これらは同じですか？異なりますか？その理由を説明してください。

**ヒント：**
- `torch.arange(12).reshape(4, 3)`で`matrix`を作成できます
- スライス`[1:3, :]`を使用します
- `id()`関数でメモリアドレスを確認します

**期待される動作：**
- `result`の形状は(4, 3)
- 2行目と3行目はすべて100になる
- `matrix`と`result`のメモリアドレスは異なる

### メモリの節約

一部の操作を実行すると、新しい結果のためにメモリが割り当てられる可能性があります。例えば、`Y = X + Y`を使用すると、`Y`が指すテンソルへの参照を解除し、代わりに新しく割り当てられたメモリ内のテンソルを指すようになります。

以下の例では、Pythonの`id()`関数を使ってこれを実証します。これはメモリ内で参照されているオブジェクトの正確なアドレスを提供します。`Y = Y + X`を実行した後、`id(Y)`が別の場所を指していることがわかります。これは、Pythonがまず`Y + X`を計算し、結果のために新しいメモリを割り当て、その後`Y`をメモリ内のこの新しい場所を指すようにするためです。

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

これは望ましくない場合があり、その理由は2つあります。

1. 第一に、常に不必要にメモリを割り当てたくはありません。機械学習では、数億個のパラメータを持つ可能性があり、1秒以内にすべてのパラメータを何度も更新します。通常の場合、これらの更新をインプレース(in-place)で実行したいと考えます。

2. インプレースで更新しない場合、他の参照は依然として古いメモリ位置を指しているため、コードの一部が意図せず古いパラメータを参照してしまう可能性があります。

幸いなことに、インプレース操作の実行は非常に簡単です。スライス表記を使用して、操作の結果を事前に割り当てられた配列に代入できます。例えば`Y[:] = <expression>`のようにします。これを説明するために、まず別の`Y`と同じ形状を持つ新しい行列`Z`を作成し、`zeros_like`を使用して全て0のブロックを割り当てます。

In [25]:
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X + Y
print("id(Z):", id(Z))

id(Z): 4668209440
id(Z): 4668209440


後続の計算で`X`を再利用しない場合、`X[:] = X + Y`または`X += Y`を使用して操作のメモリオーバーヘッドを削減することもできます。

In [26]:
before = id(X)
X += Y
id(X) == before

True

### 練習問題5

以下の要件を満たすコードを書いてください。

1. 形状が(3, 3)で、すべて1のテンソル`X`を作成してください。

2. `X`のメモリアドレスを記録してください（`id_before = id(X)`）。

3. 形状が(3, 3)で、すべて2のテンソル`Y`を作成してください。

4. 以下の3つの異なる方法で`X`と`Y`を足し算し、それぞれの後に`X`のメモリアドレスを確認してください：
   - 方法A：`X = X + Y`
   - 方法B：`X[:] = X + Y`（新しい`X`を作成してから実行）
   - 方法C：`X += Y`（新しい`X`を作成してから実行）

5. 各方法について、メモリアドレスが変わったかどうかを出力してください。

**期待される結果：**
- 方法A：メモリアドレスが変わる
- 方法B：メモリアドレスが変わらない
- 方法C：メモリアドレスが変わらない

### 他のPythonオブジェクトへの変換

深層学習フレームワークで定義されたテンソルをNumPyテンソル(`ndarray`)に変換するのは簡単で、その逆も同様に簡単です。torchテンソルとnumpy配列は基礎となるメモリを共有するため、インプレース操作で一方のテンソルを変更すると、もう一方のテンソルも同時に変更されます。

In [27]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

サイズが1のテンソルをPythonスカラーに変換するには、`item`関数またはPythonの組み込み関数を呼び出すことができます。

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 練習問題6

以下の要件を満たすコードを書いてください。

1. `torch.tensor([[1, 2, 3], [4, 5, 6]])`というテンソル`torch_tensor`を作成してください。

2. このテンソルをNumPy配列`numpy_array`に変換してください。

3. `numpy_array`の最初の要素（インデックス[0, 0]）を100に変更してください。

4. 元の`torch_tensor`の値を出力してください。値は変わっていますか？

5. `torch.tensor([[7.5]])`という単一要素のテンソル`single`を作成し、Pythonスカラーに変換してください（2つの方法で）。

**ヒント：**
- `.numpy()`メソッドを使用します
- `.item()`メソッドまたは`float()`/`int()`を使用します

**期待される動作：**
- `numpy_array`を変更すると`torch_tensor`も変わる（メモリを共有しているため）
- スカラー変換の結果は通常のPython数値型

深層学習でデータを保存・操作する主なインターフェースはテンソル(n次元配列)です。基本的な数学演算、ブロードキャスト、インデックス、スライス、メモリ節約、他のPythonオブジェクトへの変換など、様々な機能を提供します。